- name: install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - java-1.7.0-openjdk
  - unzip

- set_fact:
    solr_filename: solr-{{ solr_version }}

- set_fact:
    solr_filename: apache-solr-{{ solr_version }}
  when: solr_version | match("^(1|2|3|4\.1)")

- name: download solr
  get_url:
    url: http://archive.apache.org/dist/lucene/solr/{{ solr_version }}/{{ solr_filename }}.zip
    dest: /opt/solr.zip

- name: unpack solr
  unarchive:
    copy: no
    src: /opt/solr.zip
    dest: /opt
    creates: /opt/{{ solr_filename }}

- name: link solr
  file:
    src: /opt/{{ solr_filename }}
    dest: /opt/solr
    state: link

- name: create supervisor config
  template:
    src: solr.ini.j2
    dest: /etc/supervisord.d/solr.ini
  register: supervisor

- name: start solr
  supervisorctl:
    name: solr
    state: started

- name: reload supervisor
  supervisorctl:
    name: solr
    state: restarted
  when: supervisor.changed
